version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    volumes:
      - ./mongodata:/data/db
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - ${PORT}
    labels:
      - "traefik.enable=false"
    networks:
      - traefik
volumes:
  mongodata:

networks:
  traefik:
    external:
      name: traefik_webgateway