version: '3.3'

services:
  redis:
    image: redis:5.0
    container_name: "redis"
    labels:
      - "traefik.enable=false"
    ports:
      - 6379:6379
    networks:
      - traefik
    volumes:
      - ./data/redis/redis.conf:/opt/bitnami/redis/etc/redis.conf
      - ./data/redis/redis-persistence:/bitnami/redis/data

networks:
  traefik:
    external:
      name: traefik_webgateway